[workspace]

members = [
    "jaankaup_core",
    "hello_project",
    "fmm_project",
    "cpu_version",
    "model_loader",
    "geometry",
    "debug_shaders",
    "render_shaders",
]

[profile.dev]
opt-level = 1
debug = false

[profile.release]
opt-level = 1
debug = false
